# Site Information
site_name: "My Documentation Site"
site_description: "An example documentation site using MkDocs and Material"
site_author: "Your Name"
site_url: "http://example.com"

# Theme Configuration
theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "pink"
  font:
    text: "Roboto"
    code: "Roboto Mono"

# Plugins
plugins:
  - search
  - xrepos:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      # branch: main
      nav_repos:
        - name: test
          import_url: https://dev.azure.com/cdt-soufflet/invivo-cloud-containers/_git/docker-mkdocs
          imports: ["*"]
        - name: fast-api
          import_url: https://github.com/tiangolo/fastapi
          imports: [docs/en/docs/index.md]

# Navigation (sidebar structure)
nav:
  - Home: index.md
  - About: about.md
  - Guides:
      - "Getting Started": guides/guide1.md
  - FastAPI: fast-api/docs/en/docs/index.md
  - Test: test/README.md
  # you can still use the !import statement

# Extensions (optional)
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc
